package ru.cramen.suffeeex.ext.property

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.assertions.withClue
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import ru.cramen.suffeeex.ALL_BACKENDS
import ru.cramen.suffeeex.core.ExpressionCompiler
import ru.cramen.suffeeex.core.ExpressionException
import ru.cramen.suffeeex.core.MapEvaluationContext
import ru.cramen.suffeeex.core.backend.ExpressionBackend
import ru.cramen.suffeeex.ext.logic.LogicExtension
import ru.cramen.suffeeex.ext.math.number.NumberExtension
import ru.cramen.suffeeex.ext.math.operator.ArithmeticExtension
import ru.cramen.suffeeex.ext.variable.VariableExtension
import kotlin.test.Test

internal class PropertyAccessExtensionTest {

    // not private: the generated bytecode references these classes by name
    data class Customer(val name: String, val vip: Boolean)

    data class Order(val total: Double, val customer: Customer)

    interface HasTotal {
        val total: Double
    }

    class Invoice(override val total: Double) : HasTotal

    fun interface OrderTotal {
        fun total(order: Order): Double
    }

    private val compiler = ExpressionCompiler(
        NumberExtension, ArithmeticExtension, LogicExtension, VariableExtension, PropertyAccessExtension,
    )

    private val order = Order(42.5, Customer("ann", true))
    private val invoice = Invoice(7.5)

    private fun eval(source: String, backend: ExpressionBackend, variables: Map<String, Any> = mapOf("order" to order)): Any? =
        compiler.compile(
            source,
            variables.mapValues { it.value.javaClass.kotlin },
            backend,
        ).eval(MapEvaluationContext(variables))

    @Test
    fun `simple property`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                eval("\$order.total", backend) shouldBe 42.5
            }
        }
    }

    @Test
    fun `property chain`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                eval("\$order.customer.name", backend) shouldBe "ann"
            }
        }
    }

    @Test
    fun `property inside arithmetic`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                eval("\$order.total * 2.0", backend) shouldBe 85.0
            }
        }
    }

    @Test
    fun `member access binds tighter than infix`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                eval("\$order.total + 1.0", backend) shouldBe 43.5
            }
        }
    }

    @Test
    fun `boolean property with logic`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                eval("!\$order.customer.vip", backend) shouldBe false
                eval("\$order.customer.vip == true", backend) shouldBe true
            }
        }
    }

    @Test
    fun `property of an interface-typed variable`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                val expression = compiler.compile("\$invoice.total", mapOf("invoice" to HasTotal::class), backend)
                expression.eval(MapEvaluationContext(mapOf("invoice" to invoice))) shouldBe 7.5
            }
        }
    }

    @Test
    fun `number literals still tokenize with the dot registered`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                compiler.compile("1.5 + 1.5", backend = backend)
                    .eval(MapEvaluationContext(emptyMap())) shouldBe 3.0
            }
        }
    }

    @Test
    fun `unknown property lists the available ones`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                val exception = shouldThrow<ExpressionException> { eval("\$order.weight", backend) }
                exception.message shouldContain "weight"
                exception.message shouldContain "total"
                exception.message shouldContain "customer"
            }
        }
    }

    @Test
    fun `property access on an int variable is a compile error`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                val exception = shouldThrow<ExpressionException> {
                    compiler.compile("\$n.value", mapOf("n" to Int::class), backend)
                }
                exception.message shouldContain "Int"
            }
        }
    }

    @Test
    fun `missing member name is a compile error`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                shouldThrow<ExpressionException> { eval("\$order.", backend) }
            }
        }
    }

    @Test
    fun `specialized compile with a property parameter`() {
        for ((name, backend) in ALL_BACKENDS) {
            withClue("backend: $name") {
                val total = compiler.compile("\$order.total * 2.0", OrderTotal::class, backend)
                total.total(order) shouldBe 85.0
            }
        }
    }
}
